import type { Product } from "@/types/product";

export const mockProducts: Product[] = [
  {
    _id: "prod-1",
    name: "Aurora Wireless Headphones",
    slug: "aurora-wireless-headphones",
    description: "Premium noise-cancelling over-ear headphones with rich sound and all-day comfort.",
    price: 179,
    compareAtPrice: 249,
    images: [
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Electronics",
    brand: "Aurora",
    stock: 24,
    rating: 4.8,
    numReviews: 276,
    featured: true,
  },
  {
    _id: "prod-2",
    name: "Vanta Smartwatch",
    slug: "vanta-smartwatch",
    description: "A sleek smartwatch with sleep tracking, fitness monitoring, and an all-day battery.",
    price: 249,
    compareAtPrice: 329,
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80"],
    category: "Electronics",
    brand: "Vanta",
    stock: 18,
    rating: 4.6,
    numReviews: 154,
    featured: true,
  },
  {
    _id: "prod-3",
    name: "Luma Ceramic Lamp",
    slug: "luma-ceramic-lamp",
    description: "Ambient lighting piece with a sculpted ceramic finish for warm modern interiors.",
    price: 96,
    compareAtPrice: 129,
    images: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80"],
    category: "Home",
    brand: "Luma",
    stock: 32,
    rating: 4.7,
    numReviews: 199,
    featured: true,
  },
  {
    _id: "prod-4",
    name: "Northline Leather Tote",
    slug: "northline-leather-tote",
    description: "Structured everyday tote made from premium vegetable-tanned leather.",
    price: 130,
    compareAtPrice: 180,
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80"],
    category: "Accessories",
    brand: "Northline",
    stock: 21,
    rating: 4.5,
    numReviews: 121,
    featured: false,
  },
  {
    _id: "prod-5",
    name: "Summit Trail Runner",
    slug: "summit-trail-runner",
    description: "Lightweight running sneaker designed for comfort, traction, and all-day energy.",
    price: 142,
    compareAtPrice: 198,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80"],
    category: "Shoes",
    brand: "Summit",
    stock: 41,
    rating: 4.9,
    numReviews: 412,
    featured: true,
  },
  {
    _id: "prod-6",
    name: "Terra Coffee Set",
    slug: "terra-coffee-set",
    description: "A refined coffee ritual set with a ceramic dripper, cups, and brewer accessories.",
    price: 74,
    compareAtPrice: 99,
    images: ["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80"],
    category: "Home",
    brand: "Terra",
    stock: 17,
    rating: 4.6,
    numReviews: 88,
    featured: false,
  },
  {
    _id: "prod-7",
    name: "Aster Everyday Watch",
    slug: "aster-everyday-watch",
    description: "Minimalist timepiece with interchangeable bands and premium stainless steel case.",
    price: 189,
    compareAtPrice: 239,
    images: ["https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=900&q=80"],
    category: "Accessories",
    brand: "Aster",
    stock: 29,
    rating: 4.7,
    numReviews: 168,
    featured: true,
  },
  {
    _id: "prod-8",
    name: "Carbon Pro Laptop",
    slug: "carbon-pro-laptop",
    description: "Thin, responsive laptop engineered for work, creativity, and daily mobility.",
    price: 1299,
    compareAtPrice: 1599,
    images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80"],
    category: "Electronics",
    brand: "Carbon",
    stock: 10,
    rating: 4.8,
    numReviews: 310,
    featured: true,
  },
  {
    _id: "prod-9",
    name: "Harbor Knit Sweater",
    slug: "harbor-knit-sweater",
    description: "Soft merino blend sweater with elevated texture and a tailored silhouette.",
    price: 118,
    compareAtPrice: 156,
    images: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80"],
    category: "Fashion",
    brand: "Harbor",
    stock: 26,
    rating: 4.5,
    numReviews: 141,
    featured: false,
  },
  {
    _id: "prod-10",
    name: "Nova Travel Backpack",
    slug: "nova-travel-backpack",
    description: "Weather-resistant travel backpack with organizer compartments and padded straps.",
    price: 168,
    compareAtPrice: 219,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80"],
    category: "Accessories",
    brand: "Nova",
    stock: 35,
    rating: 4.7,
    numReviews: 230,
    featured: false,
  },
  {
    _id: "prod-11",
    name: "Sora Desk Chair",
    slug: "sora-desk-chair",
    description: "Ergonomic desk chair with supportive lumbar cushioning and a refined matte finish.",
    price: 299,
    compareAtPrice: 399,
    images: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80"],
    category: "Home",
    brand: "Sora",
    stock: 14,
    rating: 4.6,
    numReviews: 107,
    featured: false,
  },
  {
    _id: "prod-12",
    name: "Crest Wireless Earbuds",
    slug: "crest-wireless-earbuds",
    description: "Compact earbuds with crystal-clear audio, sweat resistance, and pocket-friendly charging case.",
    price: 89,
    compareAtPrice: 129,
    images: ["https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80"],
    category: "Electronics",
    brand: "Crest",
    stock: 52,
    rating: 4.8,
    numReviews: 355,
    featured: true,
  },
  {
    _id: "prod-13",
    name: "Veloura Silk Scarf",
    slug: "veloura-silk-scarf",
    description: "Lightweight statement scarf with elegant drape and a luxurious matte texture.",
    price: 66,
    compareAtPrice: 92,
    images: ["https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80"],
    category: "Fashion",
    brand: "Veloura",
    stock: 44,
    rating: 4.4,
    numReviews: 93,
    featured: false,
  },
  {
    _id: "prod-14",
    name: "Eclipse Running Shoe",
    slug: "eclipse-running-shoe",
    description: "Neutral-toned performance shoe that blends responsive cushioning with everyday style.",
    price: 158,
    compareAtPrice: 214,
    images: ["https://images.unsplash.com/photo-1543508282-6319a3e2621f?auto=format&fit=crop&w=900&q=80"],
    category: "Shoes",
    brand: "Eclipse",
    stock: 23,
    rating: 4.8,
    numReviews: 287,
    featured: true,
  },
  {
    _id: "prod-15",
    name: "Monarch Leather Belt",
    slug: "monarch-leather-belt",
    description: "Hand-finished leather belt designed to complement both office and weekend looks.",
    price: 58,
    compareAtPrice: 79,
    images: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80"],
    category: "Accessories",
    brand: "Monarch",
    stock: 60,
    rating: 4.3,
    numReviews: 72,
    featured: false,
  },
];
